module.exports = {
        nounlist =  ['air', 'wind', 'fire', 'seas', 'earth', 'ground', 'soul', 'mind', 
                    'depths', 'dark', 'rain', 'brain', 'trees', 'way', 'ink', 'shell', 'ghost', 
                    'core', 'sky', 'land', 'life', 'stones', 'rocks', 'code', 'tea', 'milk', 
                    'breeze', 'farm', 'light', 'haze', 'bush', 'thorn', 'can', 'bowl', 'stars',
                    'leaves', 'couch', 'chair', 'room', 'chest', 'cup', 'glass', 'pot', 'frame',
                    'card', 'hat', 'hosue', 'dust', 'heart', 'hearth', 'space', 'book', 'web', 'screen',
                    'sound', 'hush', 'coin', 'lair', 'maze', 'trap', 'beast', 'song', 'sign', 'keys', 'time',
                    'field', 'well', 'war', 'way', 'truth', 'lie', 'zone', 'peace', 'food', 'drink', 'wine',
                    'pen', 'word', 'car', 'truck', 'shoe', 'vat', 'map', 'game', 'end', 'start', 'mind'],

        pronounList = ['Your', 'My', 'Their', 'This', 'That', 'Some', 'Her', 'His', 'Thyne', 'Mine', 'A', 'The', 'Ye'],

        actionList = ['palpitating', 'racing, racing', 'raging, on fire', 'laughing weirdly', 'chortling hard', 
                    'alight, aghast', 'saying something', 'whispering soft', 'singing sweetly', 'trying to say', 
                    'telling the truth', 'its best darn self', 'looking for answers', 'alone in fear', 'alive in truth',
                    'looking for peace', 'aching for love', 'being the best', 'living the dream', 'speaking in tweets',
                    'trolling the web', 'being a brat', 'telling you no', 'telling you yes', 'saying "FREEDOM"', 'singing "FREEDOM',
                    'magnificent', 'already great', 'still beating fast', 'still working hard', 'trying its best', 
                    'doing the most', 'all of the things', 'never enough', 'in love...sorta', 'meeting the sun', 'slaying a ghoul',
                    'fighting a ghost', 'tripping a wire', 'hitting a wall', 'barely breaking', 'hardly enough', 'sadly melting',
                    'cannot even', 'is not worthy', 'just whispering', "knowing what's best", "not resisting",
                    'so protective', 'trying to burn', 'saying nothing', 'learning faster', 'lying to me', 'lying to them', 'lying to us',
                    'puking a bit', 'rolling over', 'jumping in space', 'skipping a beat', 'skipping a skip', 'bouncing around',
                    'laughing at you', 'laughing at me', 'laughing at them', 'laughing at him', 'not a kind soul', 'the kindest soul',
                    'like new plant life', 'like a rainbow', 'like nothing else', 'like no one else', 'like none before', "from someone's dream", 
                    "just like, can't even", 'ghost riding whip', 'phatter than phat', 'beyond the stars', 'more than merry',
                    'a true gamer', 'a master theif', 'the president', 'an attorney', 'doing just OK', 'going under', 'slowing down some',
                    'getting tired', 'getting older', 'getting worse still', 'losing the war', 'living a lie', 'living in truth', 'living magic',
                    'forgetting you', 'remembering', 'recalling you', 'not forgetting', 'glittery gold', 'not singing well', 'beating like the',
                    'giggling like', 'emblazoning', 'on the cusp of', 'made of paper', 'made of stardust', 'a peacekeeper', 'trying to change',
                    'fighting culture', 'tired, aching', 'almost running', 'almost enough', 'almost someone', 'failing like truth', 
                    'hustling hard', 'heckling me', 'being plain mean', 'rolling around', 'trying to sleep', 'starting to care',
                    'starting to hurt', 'beginning now', 'incubating', 'infiltrating', 'cascading up', 'ready. Winter', 'beating with the',
                    'leaning into', 'becoming like'],
        
        keyPhraseList = ['media', 'agenda']
}